name: Static Checks

on:
  pull_request:
  push:
    branches:
      - master
      - "v*.*.*"
    tags:
      - "v*.*.*"
  workflow:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: uv Installation
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Project installation
        run: uv sync --locked --all-extras --dev
      - name: Ruff
        run: uv run ruff check --config=pyproject.toml .
      - name: MyPy
        run: uv run mypy --config-file=pyproject.toml .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: uv Installation
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Project installation
        run: uv sync --locked --all-extras --dev

      - name: Camoufox Cache
        id: cache-camoufox
        uses: actions/cache@v4
        with:
          path: ~/.cache/camoufox
          key: camoufox-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            camoufox-${{ runner.os }}-${{ matrix.python-version }}-

      - if: ${{ steps.cache-camoufox.outputs.cache-hit != 'true' }}
        name: Camoufox Setup
        continue-on-error: true
        run: uv run camoufox fetch

      - name: PyTest
        run: uv run pytest --config-file=pyproject.toml
